- name: List Repositories
  uri:
    url: https://api.github.com/users/brandonbrinkley/repos
    method: GET
    password: "{{ REPO_TOKEN }}"
    return_content: true
    headers:
      Content-Type: application/json
